name: SimpleChairs
description: ${description}
authors: [ TehBrian, Shevchik, cnaude, spoothie ]
website: https://github.com/TehBrian/SimpleChairs

version: ${version}
main: dev.tehbrian.simplechairs.SimpleChairsPlugin
api-version: 1.21

commands:
  chairs:
    description: Various commands for SimpleChairs.
    usage: |
      /<command> reload - reload plugin configuration
      /<command> on - enable chairs for self
      /<command> off - disable chairs for self

permissions:
  chairs.reload:
    description: Permission to reload the plugin configuration.
    default: op
  chairs.sit:
    description: Permission to sit on a chair.
    default: true
