name: SimpleChairs
description: ${description}
authors: [ spoothie, cnaude, _Shevchik_, Pugabyte, TehBrian ]
website: https://github.com/TehBrian/SimpleChairs

version: ${version}
main: dev.tehbrian.simplechairs.SimpleChairs
api-version: 1.18

commands:
  chairs:
    description: Various commands for SimpleChairs.
    usage: |
      /<command> reload - reload plugin configuration
      /<command> on - enable chairs for self
      /<command> off - disable chairs for self

permissions:
  chairs.reload:
    description: Allows you to reload the plugin configuration.
    default: op
  chairs.sit:
    description: Allows you to sit on a chair.
    default: true
